/**
 * Currency metadata for the Currency Exchange screen.
 *
 * Maps every ISO 4217 currency code returned by the backend's
 * `/api/public/v1/exchange-rates/*` endpoints to a display name and a
 * representative ISO 3166-1 alpha-2 country code, used to fetch a flag
 * image from flagcdn.com (e.g. `https://flagcdn.com/w80/pk.png`).
 *
 * `country` is `null` for supranational units (e.g. XDR) that have no
 * single flag — the UI falls back to a generic icon for those.
 */
export interface CurrencyMeta {
    name: string;
    country: string | null;
}

export const CURRENCY_META: Record<string, CurrencyMeta> = {
    PKR: { name: 'Pakistani Rupee', country: 'pk' },
    AED: { name: 'UAE Dirham', country: 'ae' },
    AFN: { name: 'Afghan Afghani', country: 'af' },
    ALL: { name: 'Albanian Lek', country: 'al' },
    AMD: { name: 'Armenian Dram', country: 'am' },
    ANG: { name: 'Netherlands Antillean Guilder', country: 'cw' },
    AOA: { name: 'Angolan Kwanza', country: 'ao' },
    ARS: { name: 'Argentine Peso', country: 'ar' },
    AUD: { name: 'Australian Dollar', country: 'au' },
    AWG: { name: 'Aruban Florin', country: 'aw' },
    AZN: { name: 'Azerbaijani Manat', country: 'az' },
    BAM: { name: 'Bosnia-Herzegovina Convertible Mark', country: 'ba' },
    BBD: { name: 'Barbadian Dollar', country: 'bb' },
    BDT: { name: 'Bangladeshi Taka', country: 'bd' },
    BGN: { name: 'Bulgarian Lev', country: 'bg' },
    BHD: { name: 'Bahraini Dinar', country: 'bh' },
    BIF: { name: 'Burundian Franc', country: 'bi' },
    BMD: { name: 'Bermudan Dollar', country: 'bm' },
    BND: { name: 'Brunei Dollar', country: 'bn' },
    BOB: { name: 'Bolivian Boliviano', country: 'bo' },
    BRL: { name: 'Brazilian Real', country: 'br' },
    BSD: { name: 'Bahamian Dollar', country: 'bs' },
    BTN: { name: 'Bhutanese Ngultrum', country: 'bt' },
    BWP: { name: 'Botswanan Pula', country: 'bw' },
    BYN: { name: 'Belarusian Ruble', country: 'by' },
    BZD: { name: 'Belize Dollar', country: 'bz' },
    CAD: { name: 'Canadian Dollar', country: 'ca' },
    CDF: { name: 'Congolese Franc', country: 'cd' },
    CHF: { name: 'Swiss Franc', country: 'ch' },
    CLF: { name: 'Chilean Unit of Account (UF)', country: 'cl' },
    CLP: { name: 'Chilean Peso', country: 'cl' },
    CNH: { name: 'Chinese Yuan (Offshore)', country: 'cn' },
    CNY: { name: 'Chinese Yuan', country: 'cn' },
    COP: { name: 'Colombian Peso', country: 'co' },
    CRC: { name: 'Costa Rican Colón', country: 'cr' },
    CUP: { name: 'Cuban Peso', country: 'cu' },
    CVE: { name: 'Cape Verdean Escudo', country: 'cv' },
    CZK: { name: 'Czech Koruna', country: 'cz' },
    DJF: { name: 'Djiboutian Franc', country: 'dj' },
    DKK: { name: 'Danish Krone', country: 'dk' },
    DOP: { name: 'Dominican Peso', country: 'do' },
    DZD: { name: 'Algerian Dinar', country: 'dz' },
    EGP: { name: 'Egyptian Pound', country: 'eg' },
    ERN: { name: 'Eritrean Nakfa', country: 'er' },
    ETB: { name: 'Ethiopian Birr', country: 'et' },
    EUR: { name: 'Euro', country: 'eu' },
    FJD: { name: 'Fijian Dollar', country: 'fj' },
    FKP: { name: 'Falkland Islands Pound', country: 'fk' },
    FOK: { name: 'Faroese Króna', country: 'fo' },
    GBP: { name: 'British Pound', country: 'gb' },
    GEL: { name: 'Georgian Lari', country: 'ge' },
    GGP: { name: 'Guernsey Pound', country: 'gg' },
    GHS: { name: 'Ghanaian Cedi', country: 'gh' },
    GIP: { name: 'Gibraltar Pound', country: 'gi' },
    GMD: { name: 'Gambian Dalasi', country: 'gm' },
    GNF: { name: 'Guinean Franc', country: 'gn' },
    GTQ: { name: 'Guatemalan Quetzal', country: 'gt' },
    GYD: { name: 'Guyanaese Dollar', country: 'gy' },
    HKD: { name: 'Hong Kong Dollar', country: 'hk' },
    HNL: { name: 'Honduran Lempira', country: 'hn' },
    HRK: { name: 'Croatian Kuna', country: 'hr' },
    HTG: { name: 'Haitian Gourde', country: 'ht' },
    HUF: { name: 'Hungarian Forint', country: 'hu' },
    IDR: { name: 'Indonesian Rupiah', country: 'id' },
    ILS: { name: 'Israeli New Shekel', country: 'il' },
    IMP: { name: 'Isle of Man Pound', country: 'im' },
    INR: { name: 'Indian Rupee', country: 'in' },
    IQD: { name: 'Iraqi Dinar', country: 'iq' },
    IRR: { name: 'Iranian Rial', country: 'ir' },
    ISK: { name: 'Icelandic Króna', country: 'is' },
    JEP: { name: 'Jersey Pound', country: 'je' },
    JMD: { name: 'Jamaican Dollar', country: 'jm' },
    JOD: { name: 'Jordanian Dinar', country: 'jo' },
    JPY: { name: 'Japanese Yen', country: 'jp' },
    KES: { name: 'Kenyan Shilling', country: 'ke' },
    KGS: { name: 'Kyrgystani Som', country: 'kg' },
    KHR: { name: 'Cambodian Riel', country: 'kh' },
    KID: { name: 'Kiribati Dollar', country: 'ki' },
    KMF: { name: 'Comorian Franc', country: 'km' },
    KRW: { name: 'South Korean Won', country: 'kr' },
    KWD: { name: 'Kuwaiti Dinar', country: 'kw' },
    KYD: { name: 'Cayman Islands Dollar', country: 'ky' },
    KZT: { name: 'Kazakhstani Tenge', country: 'kz' },
    LAK: { name: 'Laotian Kip', country: 'la' },
    LBP: { name: 'Lebanese Pound', country: 'lb' },
    LKR: { name: 'Sri Lankan Rupee', country: 'lk' },
    LRD: { name: 'Liberian Dollar', country: 'lr' },
    LSL: { name: 'Lesotho Loti', country: 'ls' },
    LYD: { name: 'Libyan Dinar', country: 'ly' },
    MAD: { name: 'Moroccan Dirham', country: 'ma' },
    MDL: { name: 'Moldovan Leu', country: 'md' },
    MGA: { name: 'Malagasy Ariary', country: 'mg' },
    MKD: { name: 'Macedonian Denar', country: 'mk' },
    MMK: { name: 'Myanmar Kyat', country: 'mm' },
    MNT: { name: 'Mongolian Tugrik', country: 'mn' },
    MOP: { name: 'Macanese Pataca', country: 'mo' },
    MRU: { name: 'Mauritanian Ouguiya', country: 'mr' },
    MUR: { name: 'Mauritian Rupee', country: 'mu' },
    MVR: { name: 'Maldivian Rufiyaa', country: 'mv' },
    MWK: { name: 'Malawian Kwacha', country: 'mw' },
    MXN: { name: 'Mexican Peso', country: 'mx' },
    MYR: { name: 'Malaysian Ringgit', country: 'my' },
    MZN: { name: 'Mozambican Metical', country: 'mz' },
    NAD: { name: 'Namibian Dollar', country: 'na' },
    NGN: { name: 'Nigerian Naira', country: 'ng' },
    NIO: { name: 'Nicaraguan Córdoba', country: 'ni' },
    NOK: { name: 'Norwegian Krone', country: 'no' },
    NPR: { name: 'Nepalese Rupee', country: 'np' },
    NZD: { name: 'New Zealand Dollar', country: 'nz' },
    OMR: { name: 'Omani Rial', country: 'om' },
    PAB: { name: 'Panamanian Balboa', country: 'pa' },
    PEN: { name: 'Peruvian Sol', country: 'pe' },
    PGK: { name: 'Papua New Guinean Kina', country: 'pg' },
    PHP: { name: 'Philippine Peso', country: 'ph' },
    PLN: { name: 'Polish Zloty', country: 'pl' },
    PYG: { name: 'Paraguayan Guarani', country: 'py' },
    QAR: { name: 'Qatari Rial', country: 'qa' },
    RON: { name: 'Romanian Leu', country: 'ro' },
    RSD: { name: 'Serbian Dinar', country: 'rs' },
    RUB: { name: 'Russian Ruble', country: 'ru' },
    RWF: { name: 'Rwandan Franc', country: 'rw' },
    SAR: { name: 'Saudi Riyal', country: 'sa' },
    SBD: { name: 'Solomon Islands Dollar', country: 'sb' },
    SCR: { name: 'Seychellois Rupee', country: 'sc' },
    SDG: { name: 'Sudanese Pound', country: 'sd' },
    SEK: { name: 'Swedish Krona', country: 'se' },
    SGD: { name: 'Singapore Dollar', country: 'sg' },
    SHP: { name: 'Saint Helena Pound', country: 'sh' },
    SLE: { name: 'Sierra Leonean Leone', country: 'sl' },
    SLL: { name: 'Sierra Leonean Leone (old)', country: 'sl' },
    SOS: { name: 'Somali Shilling', country: 'so' },
    SRD: { name: 'Surinamese Dollar', country: 'sr' },
    SSP: { name: 'South Sudanese Pound', country: 'ss' },
    STN: { name: 'São Tomé & Príncipe Dobra', country: 'st' },
    SYP: { name: 'Syrian Pound', country: 'sy' },
    SZL: { name: 'Swazi Lilangeni', country: 'sz' },
    THB: { name: 'Thai Baht', country: 'th' },
    TJS: { name: 'Tajikistani Somoni', country: 'tj' },
    TMT: { name: 'Turkmenistani Manat', country: 'tm' },
    TND: { name: 'Tunisian Dinar', country: 'tn' },
    TOP: { name: 'Tongan Paʻanga', country: 'to' },
    TRY: { name: 'Turkish Lira', country: 'tr' },
    TTD: { name: 'Trinidad & Tobago Dollar', country: 'tt' },
    TVD: { name: 'Tuvaluan Dollar', country: 'tv' },
    TWD: { name: 'New Taiwan Dollar', country: 'tw' },
    TZS: { name: 'Tanzanian Shilling', country: 'tz' },
    UAH: { name: 'Ukrainian Hryvnia', country: 'ua' },
    UGX: { name: 'Ugandan Shilling', country: 'ug' },
    USD: { name: 'US Dollar', country: 'us' },
    UYU: { name: 'Uruguayan Peso', country: 'uy' },
    UZS: { name: 'Uzbekistani Som', country: 'uz' },
    VES: { name: 'Venezuelan Bolívar', country: 've' },
    VND: { name: 'Vietnamese Dong', country: 'vn' },
    VUV: { name: 'Vanuatu Vatu', country: 'vu' },
    WST: { name: 'Samoan Tala', country: 'ws' },
    XAF: { name: 'Central African CFA Franc', country: 'cm' },
    XCD: { name: 'East Caribbean Dollar', country: 'ag' },
    XCG: { name: 'Caribbean Guilder', country: 'cw' },
    XDR: { name: 'IMF Special Drawing Rights', country: null },
    XOF: { name: 'West African CFA Franc', country: 'sn' },
    XPF: { name: 'CFP Franc', country: 'pf' },
    YER: { name: 'Yemeni Rial', country: 'ye' },
    ZAR: { name: 'South African Rand', country: 'za' },
    ZMW: { name: 'Zambian Kwacha', country: 'zm' },
    ZWG: { name: 'Zimbabwe Gold', country: 'zw' },
    ZWL: { name: 'Zimbabwean Dollar', country: 'zw' },
};

/** Currencies visible to free users before watching a rewarded ad — mirrors the backend's free tier. */
export const FREE_TIER_CURRENCIES = ['PKR', 'USD', 'AED', 'SAR', 'MYR'];

export function getCurrencyMeta(code: string): CurrencyMeta {
    return CURRENCY_META[code] ?? { name: code, country: null };
}

/** flagcdn.com flag URL for a currency's representative country, or null if it has none (e.g. XDR). */
export function getCurrencyFlagUrl(code: string, width: 40 | 80 | 160 = 80): string | null {
    const { country } = getCurrencyMeta(code);
    if (!country) return null;
    return `https://flagcdn.com/w${width}/${country}.png`;
}
