/**
 * Currency metadata for the Currency Exchange screen.
 *
 * Maps every ISO 4217 currency code returned by the backend's
 * `/api/public/v1/exchange-rates/*` endpoints to a display name and a
 * representative ISO 3166-1 alpha-2 country code, used to fetch a flag
 * image from flagcdn.com (e.g. `https://flagcdn.com/w80/pk.png`).
 *
 * `country` is `null` for supranational units (e.g. XDR) that have no
 * single flag — the UI falls back to a generic icon for those.
 */
export interface CurrencyMeta {
    name: string;
    country: string | null;
    symbol?: string;
    countryName?: string;
    aliases?: string[];
}

export const CURRENCY_META: Record<string, CurrencyMeta> = {
    PKR: { name: 'Pakistani Rupee', country: 'pk', symbol: '₨', countryName: 'Pakistan', aliases: ['Pak', 'PK'] },
    AED: { name: 'UAE Dirham', country: 'ae', symbol: 'د.إ', countryName: 'United Arab Emirates', aliases: ['UAE', 'Dubai', 'Abu Dhabi', 'Emirates'] },
    AFN: { name: 'Afghan Afghani', country: 'af', symbol: '؋', countryName: 'Afghanistan', aliases: ['Afghan'] },
    ALL: { name: 'Albanian Lek', country: 'al', symbol: 'L', countryName: 'Albania' },
    AMD: { name: 'Armenian Dram', country: 'am', symbol: '֏', countryName: 'Armenia' },
    ANG: { name: 'Netherlands Antillean Guilder', country: 'cw', symbol: 'ƒ', countryName: 'Curaçao' },
    AOA: { name: 'Angolan Kwanza', country: 'ao', symbol: 'Kz', countryName: 'Angola' },
    ARS: { name: 'Argentine Peso', country: 'ar', symbol: '$', countryName: 'Argentina' },
    AUD: { name: 'Australian Dollar', country: 'au', symbol: 'A$', countryName: 'Australia', aliases: ['Aussie'] },
    AWG: { name: 'Aruban Florin', country: 'aw', symbol: 'ƒ', countryName: 'Aruba' },
    AZN: { name: 'Azerbaijani Manat', country: 'az', symbol: '₼', countryName: 'Azerbaijan' },
    BAM: { name: 'Bosnia-Herzegovina Convertible Mark', country: 'ba', symbol: 'KM', countryName: 'Bosnia and Herzegovina' },
    BBD: { name: 'Barbadian Dollar', country: 'bb', symbol: 'Bds$', countryName: 'Barbados' },
    BDT: { name: 'Bangladeshi Taka', country: 'bd', symbol: '৳', countryName: 'Bangladesh', aliases: ['BD'] },
    BGN: { name: 'Bulgarian Lev', country: 'bg', symbol: 'лв', countryName: 'Bulgaria' },
    BHD: { name: 'Bahraini Dinar', country: 'bh', symbol: 'د.ب', countryName: 'Bahrain' },
    BIF: { name: 'Burundian Franc', country: 'bi', symbol: 'FBu', countryName: 'Burundi' },
    BMD: { name: 'Bermudan Dollar', country: 'bm', symbol: '$', countryName: 'Bermuda' },
    BND: { name: 'Brunei Dollar', country: 'bn', symbol: 'B$', countryName: 'Brunei' },
    BOB: { name: 'Bolivian Boliviano', country: 'bo', symbol: 'Bs.', countryName: 'Bolivia' },
    BRL: { name: 'Brazilian Real', country: 'br', symbol: 'R$', countryName: 'Brazil' },
    BSD: { name: 'Bahamian Dollar', country: 'bs', symbol: 'B$', countryName: 'Bahamas' },
    BTN: { name: 'Bhutanese Ngultrum', country: 'bt', symbol: 'Nu.', countryName: 'Bhutan' },
    BWP: { name: 'Botswanan Pula', country: 'bw', symbol: 'P', countryName: 'Botswana' },
    BYN: { name: 'Belarusian Ruble', country: 'by', symbol: 'Br', countryName: 'Belarus' },
    BZD: { name: 'Belize Dollar', country: 'bz', symbol: 'BZ$', countryName: 'Belize' },
    CAD: { name: 'Canadian Dollar', country: 'ca', symbol: 'C$', countryName: 'Canada', aliases: ['CA'] },
    CDF: { name: 'Congolese Franc', country: 'cd', symbol: 'FC', countryName: 'Congo' },
    CHF: { name: 'Swiss Franc', country: 'ch', symbol: 'CHF', countryName: 'Switzerland', aliases: ['Swiss'] },
    CLF: { name: 'Chilean Unit of Account (UF)', country: 'cl', symbol: 'UF', countryName: 'Chile' },
    CLP: { name: 'Chilean Peso', country: 'cl', symbol: '$', countryName: 'Chile' },
    CNH: { name: 'Chinese Yuan (Offshore)', country: 'cn', symbol: '¥', countryName: 'China', aliases: ['RMB'] },
    CNY: { name: 'Chinese Yuan', country: 'cn', symbol: '¥', countryName: 'China', aliases: ['RMB', 'Yuan'] },
    COP: { name: 'Colombian Peso', country: 'co', symbol: '$', countryName: 'Colombia' },
    CRC: { name: 'Costa Rican Colón', country: 'cr', symbol: '₡', countryName: 'Costa Rica' },
    CUP: { name: 'Cuban Peso', country: 'cu', symbol: '$MN', countryName: 'Cuba' },
    CVE: { name: 'Cape Verdean Escudo', country: 'cv', symbol: '$', countryName: 'Cape Verde' },
    CZK: { name: 'Czech Koruna', country: 'cz', symbol: 'Kč', countryName: 'Czech Republic', aliases: ['Czechia'] },
    DJF: { name: 'Djiboutian Franc', country: 'dj', symbol: 'Fdj', countryName: 'Djibouti' },
    DKK: { name: 'Danish Krone', country: 'dk', symbol: 'kr', countryName: 'Denmark' },
    DOP: { name: 'Dominican Peso', country: 'do', symbol: 'RD$', countryName: 'Dominican Republic' },
    DZD: { name: 'Algerian Dinar', country: 'dz', symbol: 'د.ج', countryName: 'Algeria' },
    EGP: { name: 'Egyptian Pound', country: 'eg', symbol: 'E£', countryName: 'Egypt' },
    ERN: { name: 'Eritrean Nakfa', country: 'er', symbol: 'Nfk', countryName: 'Eritrea' },
    ETB: { name: 'Ethiopian Birr', country: 'et', symbol: 'Br', countryName: 'Ethiopia' },
    EUR: { name: 'Euro', country: 'eu', symbol: '€', countryName: 'European Union', aliases: ['Europe', 'EU', 'Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'Ireland'] },
    FJD: { name: 'Fijian Dollar', country: 'fj', symbol: 'FJ$', countryName: 'Fiji' },
    FKP: { name: 'Falkland Islands Pound', country: 'fk', symbol: '£', countryName: 'Falkland Islands' },
    FOK: { name: 'Faroese Króna', country: 'fo', symbol: 'kr', countryName: 'Faroe Islands' },
    GBP: { name: 'British Pound', country: 'gb', symbol: '£', countryName: 'United Kingdom', aliases: ['UK', 'Britain', 'England', 'Pound Sterling'] },
    GEL: { name: 'Georgian Lari', country: 'ge', symbol: '₾', countryName: 'Georgia' },
    GGP: { name: 'Guernsey Pound', country: 'gg', symbol: '£', countryName: 'Guernsey' },
    GHS: { name: 'Ghanaian Cedi', country: 'gh', symbol: '₵', countryName: 'Ghana' },
    GIP: { name: 'Gibraltar Pound', country: 'gi', symbol: '£', countryName: 'Gibraltar' },
    GMD: { name: 'Gambian Dalasi', country: 'gm', symbol: 'D', countryName: 'Gambia' },
    GNF: { name: 'Guinean Franc', country: 'gn', symbol: 'FG', countryName: 'Guinea' },
    GTQ: { name: 'Guatemalan Quetzal', country: 'gt', symbol: 'Q', countryName: 'Guatemala' },
    GYD: { name: 'Guyanaese Dollar', country: 'gy', symbol: 'G$', countryName: 'Guyana' },
    HKD: { name: 'Hong Kong Dollar', country: 'hk', symbol: 'HK$', countryName: 'Hong Kong' },
    HNL: { name: 'Honduran Lempira', country: 'hn', symbol: 'L', countryName: 'Honduras' },
    HRK: { name: 'Croatian Kuna', country: 'hr', symbol: 'kn', countryName: 'Croatia' },
    HTG: { name: 'Haitian Gourde', country: 'ht', symbol: 'G', countryName: 'Haiti' },
    HUF: { name: 'Hungarian Forint', country: 'hu', symbol: 'Ft', countryName: 'Hungary' },
    IDR: { name: 'Indonesian Rupiah', country: 'id', symbol: 'Rp', countryName: 'Indonesia' },
    ILS: { name: 'Israeli New Shekel', country: 'il', symbol: '₪', countryName: 'Israel' },
    IMP: { name: 'Isle of Man Pound', country: 'im', symbol: '£', countryName: 'Isle of Man' },
    INR: { name: 'Indian Rupee', country: 'in', symbol: '₹', countryName: 'India', aliases: ['IND'] },
    IQD: { name: 'Iraqi Dinar', country: 'iq', symbol: 'د.ع', countryName: 'Iraq' },
    IRR: { name: 'Iranian Rial', country: 'ir', symbol: '﷼', countryName: 'Iran' },
    ISK: { name: 'Icelandic Króna', country: 'is', symbol: 'kr', countryName: 'Iceland' },
    JEP: { name: 'Jersey Pound', country: 'je', symbol: '£', countryName: 'Jersey' },
    JMD: { name: 'Jamaican Dollar', country: 'jm', symbol: 'J$', countryName: 'Jamaica' },
    JOD: { name: 'Jordanian Dinar', country: 'jo', symbol: 'د.ا', countryName: 'Jordan' },
    JPY: { name: 'Japanese Yen', country: 'jp', symbol: '¥', countryName: 'Japan', aliases: ['Yen'] },
    KES: { name: 'Kenyan Shilling', country: 'ke', symbol: 'KSh', countryName: 'Kenya' },
    KGS: { name: 'Kyrgystani Som', country: 'kg', symbol: 'сом', countryName: 'Kyrgyzstan' },
    KHR: { name: 'Cambodian Riel', country: 'kh', symbol: '៛', countryName: 'Cambodia' },
    KID: { name: 'Kiribati Dollar', country: 'ki', symbol: '$', countryName: 'Kiribati' },
    KMF: { name: 'Comorian Franc', country: 'km', symbol: 'CF', countryName: 'Comoros' },
    KRW: { name: 'South Korean Won', country: 'kr', symbol: '₩', countryName: 'South Korea', aliases: ['Korea'] },
    KWD: { name: 'Kuwaiti Dinar', country: 'kw', symbol: 'د.ك', countryName: 'Kuwait', aliases: ['KD'] },
    KYD: { name: 'Cayman Islands Dollar', country: 'ky', symbol: 'CI$', countryName: 'Cayman Islands' },
    KZT: { name: 'Kazakhstani Tenge', country: 'kz', symbol: '₸', countryName: 'Kazakhstan' },
    LAK: { name: 'Laotian Kip', country: 'la', symbol: '₭', countryName: 'Laos' },
    LBP: { name: 'Lebanese Pound', country: 'lb', symbol: 'ل.ل', countryName: 'Lebanon' },
    LKR: { name: 'Sri Lankan Rupee', country: 'lk', symbol: 'Rs', countryName: 'Sri Lanka' },
    LRD: { name: 'Liberian Dollar', country: 'lr', symbol: 'L$', countryName: 'Liberia' },
    LSL: { name: 'Lesotho Loti', country: 'ls', symbol: 'L', countryName: 'Lesotho' },
    LYD: { name: 'Libyan Dinar', country: 'ly', symbol: 'ل.د', countryName: 'Libya' },
    MAD: { name: 'Moroccan Dirham', country: 'ma', symbol: 'د.م.', countryName: 'Morocco' },
    MDL: { name: 'Moldovan Leu', country: 'md', symbol: 'L', countryName: 'Moldova' },
    MGA: { name: 'Malagasy Ariary', country: 'mg', symbol: 'Ar', countryName: 'Madagascar' },
    MKD: { name: 'Macedonian Denar', country: 'mk', symbol: 'ден', countryName: 'North Macedonia' },
    MMK: { name: 'Myanmar Kyat', country: 'mm', symbol: 'Ks', countryName: 'Myanmar', aliases: ['Burma'] },
    MNT: { name: 'Mongolian Tugrik', country: 'mn', symbol: '₮', countryName: 'Mongolia' },
    MOP: { name: 'Macanese Pataca', country: 'mo', symbol: 'MOP$', countryName: 'Macau' },
    MRU: { name: 'Mauritanian Ouguiya', country: 'mr', symbol: 'UM', countryName: 'Mauritania' },
    MUR: { name: 'Mauritian Rupee', country: 'mu', symbol: '₨', countryName: 'Mauritius' },
    MVR: { name: 'Maldivian Rufiyaa', country: 'mv', symbol: 'Rf', countryName: 'Maldives' },
    MWK: { name: 'Malawian Kwacha', country: 'mw', symbol: 'MK', countryName: 'Malawi' },
    MXN: { name: 'Mexican Peso', country: 'mx', symbol: 'Mex$', countryName: 'Mexico' },
    MYR: { name: 'Malaysian Ringgit', country: 'my', symbol: 'RM', countryName: 'Malaysia' },
    MZN: { name: 'Mozambican Metical', country: 'mz', symbol: 'MT', countryName: 'Mozambique' },
    NAD: { name: 'Namibian Dollar', country: 'na', symbol: 'N$', countryName: 'Namibia' },
    NGN: { name: 'Nigerian Naira', country: 'ng', symbol: '₦', countryName: 'Nigeria' },
    NIO: { name: 'Nicaraguan Córdoba', country: 'ni', symbol: 'C$', countryName: 'Nicaragua' },
    NOK: { name: 'Norwegian Krone', country: 'no', symbol: 'kr', countryName: 'Norway' },
    NPR: { name: 'Nepalese Rupee', country: 'np', symbol: 'Rs', countryName: 'Nepal' },
    NZD: { name: 'New Zealand Dollar', country: 'nz', symbol: 'NZ$', countryName: 'New Zealand' },
    OMR: { name: 'Omani Rial', country: 'om', symbol: 'ر.ع.', countryName: 'Oman' },
    PAB: { name: 'Panamanian Balboa', country: 'pa', symbol: 'B/.', countryName: 'Panama' },
    PEN: { name: 'Peruvian Sol', country: 'pe', symbol: 'S/.', countryName: 'Peru' },
    PGK: { name: 'Papua New Guinean Kina', country: 'pg', symbol: 'K', countryName: 'Papua New Guinea' },
    PHP: { name: 'Philippine Peso', country: 'ph', symbol: '₱', countryName: 'Philippines' },
    PLN: { name: 'Polish Zloty', country: 'pl', symbol: 'zł', countryName: 'Poland' },
    PYG: { name: 'Paraguayan Guarani', country: 'py', symbol: '₲', countryName: 'Paraguay' },
    QAR: { name: 'Qatari Rial', country: 'qa', symbol: 'ر.ق', countryName: 'Qatar', aliases: ['QR'] },
    RON: { name: 'Romanian Leu', country: 'ro', symbol: 'lei', countryName: 'Romania' },
    RSD: { name: 'Serbian Dinar', country: 'rs', symbol: 'дин.', countryName: 'Serbia' },
    RUB: { name: 'Russian Ruble', country: 'ru', symbol: '₽', countryName: 'Russia' },
    RWF: { name: 'Rwandan Franc', country: 'rw', symbol: 'FRw', countryName: 'Rwanda' },
    SAR: { name: 'Saudi Riyal', country: 'sa', symbol: 'ر.س', countryName: 'Saudi Arabia', aliases: ['KSA', 'Saudi', 'Riyal'] },
    SBD: { name: 'Solomon Islands Dollar', country: 'sb', symbol: 'SI$', countryName: 'Solomon Islands' },
    SCR: { name: 'Seychellois Rupee', country: 'sc', symbol: 'SR', countryName: 'Seychelles' },
    SDG: { name: 'Sudanese Pound', country: 'sd', symbol: 'ج.س.', countryName: 'Sudan' },
    SEK: { name: 'Swedish Krona', country: 'se', symbol: 'kr', countryName: 'Sweden' },
    SGD: { name: 'Singapore Dollar', country: 'sg', symbol: 'S$', countryName: 'Singapore' },
    SHP: { name: 'Saint Helena Pound', country: 'sh', symbol: '£', countryName: 'Saint Helena' },
    SLE: { name: 'Sierra Leonean Leone', country: 'sl', symbol: 'Le', countryName: 'Sierra Leone' },
    SLL: { name: 'Sierra Leonean Leone (old)', country: 'sl', symbol: 'Le', countryName: 'Sierra Leone' },
    SOS: { name: 'Somali Shilling', country: 'so', symbol: 'Sh.So.', countryName: 'Somalia' },
    SRD: { name: 'Surinamese Dollar', country: 'sr', symbol: 'SRD$', countryName: 'Suriname' },
    SSP: { name: 'South Sudanese Pound', country: 'ss', symbol: 'SS£', countryName: 'South Sudan' },
    STN: { name: 'São Tomé & Príncipe Dobra', country: 'st', symbol: 'Db', countryName: 'São Tomé and Príncipe' },
    SYP: { name: 'Syrian Pound', country: 'sy', symbol: 'LS', countryName: 'Syria' },
    SZL: { name: 'Swazi Lilangeni', country: 'sz', symbol: 'E', countryName: 'Eswatini' },
    THB: { name: 'Thai Baht', country: 'th', symbol: '฿', countryName: 'Thailand' },
    TJS: { name: 'Tajikistani Somoni', country: 'tj', symbol: 'SM', countryName: 'Tajikistan' },
    TMT: { name: 'Turkmenistani Manat', country: 'tm', symbol: 'T', countryName: 'Turkmenistan' },
    TND: { name: 'Tunisian Dinar', country: 'tn', symbol: 'د.ت', countryName: 'Tunisia' },
    TOP: { name: 'Tongan Paʻanga', country: 'to', symbol: 'T$', countryName: 'Tonga' },
    TRY: { name: 'Turkish Lira', country: 'tr', symbol: '₺', countryName: 'Turkey', aliases: ['Türkiye', 'Lira'] },
    TTD: { name: 'Trinidad & Tobago Dollar', country: 'tt', symbol: 'TT$', countryName: 'Trinidad and Tobago' },
    TVD: { name: 'Tuvaluan Dollar', country: 'tv', symbol: '$', countryName: 'Tuvalu' },
    TWD: { name: 'New Taiwan Dollar', country: 'tw', symbol: 'NT$', countryName: 'Taiwan' },
    TZS: { name: 'Tanzanian Shilling', country: 'tz', symbol: 'TSh', countryName: 'Tanzania' },
    UAH: { name: 'Ukrainian Hryvnia', country: 'ua', symbol: '₴', countryName: 'Ukraine' },
    UGX: { name: 'Ugandan Shilling', country: 'ug', symbol: 'USh', countryName: 'Uganda' },
    USD: { name: 'US Dollar', country: 'us', symbol: '$', countryName: 'United States', aliases: ['USA', 'US', 'America', 'Dollar'] },
    UYU: { name: 'Uruguayan Peso', country: 'uy', symbol: '$U', countryName: 'Uruguay' },
    UZS: { name: 'Uzbekistani Som', country: 'uz', symbol: 'soʻm', countryName: 'Uzbekistan' },
    VES: { name: 'Venezuelan Bolívar', country: 've', symbol: 'Bs.S', countryName: 'Venezuela' },
    VND: { name: 'Vietnamese Dong', country: 'vn', symbol: '₫', countryName: 'Vietnam' },
    VUV: { name: 'Vanuatu Vatu', country: 'vu', symbol: 'VT', countryName: 'Vanuatu' },
    WST: { name: 'Samoan Tala', country: 'ws', symbol: 'WS$', countryName: 'Samoa' },
    XAF: { name: 'Central African CFA Franc', country: 'cm', symbol: 'FCFA', countryName: 'Central African Republic' },
    XCD: { name: 'East Caribbean Dollar', country: 'ag', symbol: 'EC$', countryName: 'East Caribbean' },
    XCG: { name: 'Caribbean Guilder', country: 'cw', symbol: 'Cg', countryName: 'Curaçao' },
    XDR: { name: 'IMF Special Drawing Rights', country: null, symbol: 'SDR', countryName: 'International Monetary Fund' },
    XOF: { name: 'West African CFA Franc', country: 'sn', symbol: 'CFA', countryName: 'West Africa' },
    XPF: { name: 'CFP Franc', country: 'pf', symbol: '₣', countryName: 'French Polynesia' },
    YER: { name: 'Yemeni Rial', country: 'ye', symbol: '﷼', countryName: 'Yemen' },
    ZAR: { name: 'South African Rand', country: 'za', symbol: 'R', countryName: 'South Africa' },
    ZMW: { name: 'Zambian Kwacha', country: 'zm', symbol: 'ZK', countryName: 'Zambia' },
    ZWG: { name: 'Zimbabwe Gold', country: 'zw', symbol: 'ZiG', countryName: 'Zimbabwe' },
    ZWL: { name: 'Zimbabwean Dollar', country: 'zw', symbol: 'Z$', countryName: 'Zimbabwe' },
};

/** Currencies visible to free users before watching a rewarded ad — mirrors the backend's free tier. */
export const FREE_TIER_CURRENCIES = ['PKR', 'USD', 'AED', 'SAR', 'MYR'];

export function getCurrencyMeta(code: string): CurrencyMeta {
    return CURRENCY_META[code] ?? { name: code, country: null };
}

/** flagcdn.com flag URL for a currency's representative country, or null if it has none (e.g. XDR). */
export function getCurrencyFlagUrl(code: string, width: 40 | 80 | 160 = 80): string | null {
    const { country } = getCurrencyMeta(code);
    if (!country) return null;
    return `https://flagcdn.com/w${width}/${country}.png`;
}
